### ISSUE TITLE
plugin error in IntelliJ IDEA

### ISSUE THREAD

**Issue by jirkadev** [iguissouma/meteorjs-plugin#3]
Hello, I got many of these errors, I haven't pinpointed when they occur, so far I just dismissed them in the Idea log. 
The plugin still works fine.

I haven't looked closely into this.
@iguissouma Would you publish a fix to this plugin if I create a PR?
```
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable org.igu.meteorjs.settings.MeteorJSTemplateConfigurable;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: com.igu.meteorjs]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:87)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:119)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:104)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:407)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.optionsFlow(ActionAsyncProvider.kt:288)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.access$optionsFlow(ActionAsyncProvider.kt:37)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$filterElements$1$1$optionsPromise$1.invokeSuspend(ActionAsyncProvider.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by iguissouma** [comment]
@jirikrepl Yes I can publish a new version if you provide a PR

**Comment by jirkadev** [comment]
Hello, I created a PR https://github.com/iguissouma/meteorjs-plugin/pull/4
I also built the jar and installed an updated plugin locally. 
It seems to be woking fine and the error is gone.
